### ISSUE TITLE
Pre-processing

### ISSUE THREAD

**Issue by Rahulb7** [rmodi6/Email-Classification#3]
Hey. I am trying to make a project On the same (EMail Classification Using Machine learning). Except I am using RNN. I want your help about how should I start the Pre-Processing step. Thanks in advance.

**Comment by rmodi6** [comment]
Hey Rahul,

There are plenty of pre-processing techniques that are used in Natural Language Processing for cleaning and modifying texts depending on the application. The most common ones that are used in majority of applications are:
- stop-words removal
- stemming
- lemmatization

I'd suggest you have a look at each of them (and others) and decide which ones you want to use based on your dataset and application. You'll find libraries for implementing each of these techniques easily in Python. **NLTK** and **Porter Stemmer** are some of the libraries used in this project. You can also have a look at `extract.py` where these libraries have been used for pre-processing.

Best,
Ruchit

**Comment by Rahulb7** [comment]
Thanks man, I appreciate it!!
